version: '2'
services:
    karmaspringboot-app:
        image: karmaspringboot
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://karmaspringboot-postgresql:5432/KarmaSpringboot
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    karmaspringboot-postgresql:
        extends:
            file: postgresql.yml
            service: karmaspringboot-postgresql
