environments:
- name: acceptance
  loadbalancer:
    hostedzone: bigbluesign.com
    certificate: "8c43c2a3-1a25-4552-9ee9-804124d4d1d7"
  cluster:
    minSize: 2
    desiredCapacity: 2

service:
  name: karma-angular
  cpu: 256
  memory: 256
  port: 8080
  healthEndpoint: /health
  hostPatterns:
  - karma.*
  database:
    name: karma
    masterUsername: karma
    engine: postgres
  environment:
    SPRING_DATASOURCE_USERNAME: ${DatabaseMasterUsername}
    SPRING_DATASOURCE_PASSWORD: ${DatabaseMasterPassword}
    SPRING_DATASOURCE_URL: jdbc:postgresql://${DatabaseEndpointAddress}:${DatabaseEndpointPort}/${DatabaseName}
  pipeline:
    build:
      image: aws/codebuild/java:openjdk-8
    acceptance:
      image: aws/codebuild/java:openjdk-8
    production:
      disabled: true
    notify:
    - cplee@nektos.com
    - pgrogan@stanfieldsystems.com

### configure extension for handling CloudFront and static assets
extensions:
- url: https://github.com/stelligent/mu-cloudfront/archive/v0.3.zip
parameters:
  mu-loadbalancer-acceptance:
    CloudFrontCert: "86a733d7-b890-478b-bc24-4ec0b40ea66d"
  mu-pipeline-.*:
    SourcePath: karma-angular/dist

### custom cloudformation for managing the bucket with BDD reports
templates:
  mu-pipeline-karma-angular:
    Resources:
      PipelineFailedEventRule:
        Properties:
          Targets:
            Fn::Splice:
            - 0
            - 1
            - - InputTransformer:
                  InputTemplate:
                    Fn::Sub: >
                      "Pipeline <pipeline> has failed. Test results available at https://s3-${AWS::Region}.amazonaws.com/${CIBucket}/${ServiceName}/index.html.  Details available at https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/<pipeline>"
      PipelineSucceededEventRule:
        Properties:
          Targets:
            Fn::Splice:
            - 0
            - 1
            - - InputTransformer:
                  InputTemplate:
                    Fn::Sub: >
                      "Pipeline <pipeline> has succeeded. Test results available at https://s3-${AWS::Region}.amazonaws.com/${CIBucket}/${ServiceName}/index.html.  Details available at https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/<pipeline>"
      CIBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName:
            Fn::Sub: stanfield-systems-karma-ci
          WebsiteConfiguration:
            IndexDocument: index.html
      CIBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket:
            Ref: CIBucket
          PolicyDocument:
            Statement:
              - Effect: Allow
                Principal:
                  AWS:
                    Ref: CodeBuildCIRoleArn
                Action:
                - s3:ListBucket
                Resource:
                  Fn::Sub: arn:aws:s3:::${CIBucket}
              - Effect: Allow
                Principal:
                  AWS:
                    Ref: CodeBuildCIRoleArn
                Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                Resource:
                  Fn::Sub: arn:aws:s3:::${CIBucket}/*
              - Effect: Allow
                Principal: '*'
                Action: s3:GetObject
                Resource:
                  Fn::Sub: arn:aws:s3:::${CIBucket}/*
                Condition:
                  IpAddress:
                    aws:SourceIp:
                    - 73.151.106.136/32
                    - 96.81.182.193/32
